### ISSUE TITLE
Questions on Homework 2

### ISSUE THREAD

**Issue by WDYBQJ** [danielepanozzo/gp-old#1]
I have encountered the following problems when implementing homework 2.
- In assignment2.pdf, you say that "if no constraint points are within wendlandRadius of the evaluation grid point, you can assign a large positive (outside) value to the grid point". I think that if you are inside the object, it is still possible that no constraint points are within wendlandRadius, since you are away from the border. So I do not think assigning a large positive value is correct.
- The MLS method would generate a lot of small pieces around the object especially when the degree >= 2. And this situation cannot be resolved by increasing the radius.

**Comment by jpanetta** [comment]
1) Correct, generally there will be interior points further than wendlandRadius from the surface. Assigning a large value to these as suggested will create a shell inside the object that could be removed in a post-process.

2) This is expected behavior: high degree interpolants can behave strangely away from the constraints. It should be possible to filter these as well (for some values of the radius, anyway).
