### ISSUE TITLE
How to Choose B-Spline Basis for Screened Poisson?

### ISSUE THREAD

**Issue by WDYBQJ** [danielepanozzo/gp-old#10]
In the paper it says we should choose a collection of B-spline {B_1, B_2, \dots, B_N} functions for computing, so that the result is a linear combination of these function. But I did not see how these basis are chosen. Could you please tell me how to choose B_i given a collection of oriented points?

**Comment by jpanetta** [comment]
Just in case it wasn't clear: you're not expected to implement Poisson surface reconstruction for this assignment. The optional task only asks you to try one of the implementations we indicated (e.g., in [MeshLab](http://www.meshlab.net)).

In case you're still curious, the general idea is as follows: you construct a grid at some resolution surrounding the point cloud. Then you create "tensor product B-spline" basis functions on this grid. The simplest example is the trilinear basis. For this, you would create a basis function for each grid node. The basis function, phi_i, sitting on grid node p_i satisfies:
phi_i(p_i) = 1
phi_i(p_j) = 0 for all j != i
and it does this by linearly interpolating from 1 to 0 along each of the 6 incident grid edges. Over the interior of a grid cell adjacent p_i, phi_i looks like the product of 3 linear interpolations (one for each direction):
phi_i([x,y,z]) = (1 - |x - p_i.x|/h) * (1 - |y - p_i.y|/h) * (1 - |z - p_i.z|/h)
where h is the grid edge length.

The basis the paper suggests is more complicated, though:
1) It mentions a triquadratic basis; this means you create additional nodes (and corresponding basis functions) at each grid edge midpoint, face midpoint and cell midpoint for a total of 8 + 12 + 6 + 1 = 27 nodes on a given cell (but shared with the neighbors). The basis function for each node is now the product of three quadratic expressions (for x, y, and z), but still satisfies the property of evaluating to 1 on the node and 0 on all others.
2) Instead of a uniform grid, it constructs this basis on an adaptively refined octree. Essentially, the grid is refined near the point cloud to represent more detailed functions near the surface and remains coarse away from the point cloud to reduce the size of the linear system.
