### ISSUE TITLE
General Questions about Assignment 1

### ISSUE THREAD

**Issue by yunjianyang** [danielepanozzo/gp-old#27]
Hi everyone,

I have some troubles towards understanding our assignment1. Any help will be appreciated!

> Create a private repository in https://github.com/NYUGP17 called AssignmentN_USER

Do we have our repository for this year? Or we just create in 

> When the build completes successfully, begin implementing the missing blocks in src/main.cpp as described by the assignment PDF.

I'm sorry I didn't find the assignment PDF...

And finally, when is the due date for assignment 1?

Thanks!
Yunjian

**Comment by danielepanozzo** [comment]
1. It is not mandatory to submit this assignment. If you want you can do it and Zhongshi can give you feedback on the code. @jiangzhongshi will follow up with instructions on how to set up the repository.

2. https://cs.nyu.edu/%7Epanozzo/gp18/Handout1.pdf The link is in the assignments section of readme.md

3. There is no due date since it is optional and will not count for the final grade.
