### ISSUE TITLE
Conflicts between key_down and imgui

### ISSUE THREAD

**Issue by abhijit-c** [danielepanozzo/gp-old#39]
Hello all,

Hopefully finals week is going well for all. I've been running into a strange issue in the implementation of my project, specifically a conflict between key_down and imgui.

Basically the situation is I have an exposed global on my imgui bar which I would like to modify, for example changing it to 20. However, because I also have an key_down defined for '2', when I enter the '2' in the 20 the key_down instructions begin executing. Any advice on how to avoid this, or am I just going to have to rebind all of the key_down instructions? 

My key_down implementation is the same as from assignment 4, and the imgui bar build was taken directly from the sample one in the tutorial

**Comment by jiangzhongshi** [comment]
This is interesting, though I don't have a better workaround in mind than rebinding them (or adding a modifier key during `key_down`). It may worth to report to libigl but I don't expect it to be fixed before the deadline.

**Comment by jdumas** [comment]
This looks like [bug #764](https://github.com/libigl/libigl/issues/764) in libigl. The current workaround if you do not want to modify the libigl source code would be to use a plugin instead of a lambda to define your keyboard/mouse interaction, and put your plugin right after the imgui plugin (so that the method have lower priority).

**Comment by abhijit-c** [comment]
I get it, I will try jdumas' suggestions!

Thanks.
