### ISSUE TITLE
Question regarding Radial Basis Function interpolation in lecture notes

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/gp-old#45]
I've read https://github.com/danielepanozzo/gp/issues/5, and the explanation helps me a lot.
But I still have a few questions.

![image](https://user-images.githubusercontent.com/25846932/53306576-cb45b280-385c-11e9-95c5-31c1df5a0a82.png)

* Regarding the above function(page 19 of Lecture 3), what is the meaning of `d_j (0 <= j <= N-1)` on the right side of the equation? Is it known?

 * Is the meaning of `||c_i - c_k||` the distance between different dots `c_i` and `c_k`?

* Is our target to solve the linear equation above(where `omega_j` are the unknowns)?

![image](https://user-images.githubusercontent.com/25846932/53306660-f54ba480-385d-11e9-8138-d665b9ffe38a.png)

* My understanding is that once we solved the equation and have all the `omega_j`s, we have a closed form of function `F(x)`(as in the above screen shot). So that we can use marching cubes to find the surface. Is my understanding correct?

Thank you.

**Comment by danielepanozzo** [comment]
* Regarding the above function(page 19 of Lecture 3), what is the meaning of `d_j (0 <= j <= N-1)` on the right side of the equation? Is it known?

Yes, this is the value that your functions should have at the point corresponding to equation j (usually 0, -eps, or +eps)

* Is the meaning of `||c_i - c_k||` the distance between different dots `c_i` and `c_k`?

Yes

* Is our target to solve the linear equation above(where `omega_j` are the unknowns)?

Yes

* My understanding is that once we solved the equation and have all the `omega_j`s, we have a closed form of function `F(x)`(as in the above screen shot). So that we can use marching cubes to find the surface. Is my understanding correct?

Yes

**Comment by LihengGong** [comment]
Thank you professor. That's very helpful.
