### ISSUE TITLE
Trying to understand Radial Basis Function interpolation

### ISSUE THREAD

**Issue by oveddan** [danielepanozzo/gp-old#5]
I'm having a difficult time understanding the different parts of the RBF interpolation as explained on slide 18 of [03 - Reconstruction](http://cs.nyu.edu/~panozzo/gp/03%20-%20Reconstruction.pdf):

What is `j` representing?  Is it each constraint?  Does "for all `j`" mean for all constraints?
Is the big `N` the number of constraints?
And finally, what is the `d`, and how does it correspond to epsilon?

**Comment by oveddan** [comment]
I think I understand (let me know if I'm wrong):
For each constraint, `dj` = Epsilon for that constraint,
The left side is summing up the RBFs of the squared difference of that constraint with every other constraint  `||cj-ci||`  times some weight (`wi`) corresponding to the other constraint `ci`.  We are trying to approximate the best solution for the weights.

**Comment by jpanetta** [comment]
The RBF equations are perhaps confusing because they create a separate basis function on each constraint point (c_i) of the form b_i(x) = phi(||x - c_i||), then also evaluate these basis functions at all constraint points (c_j). For our MLS assignment, the basis functions aren't tied to the constraint points (they're just global polynomials), so there's no confusion about "which c" refers to the evaluation point and which labels the basis function.

The left hand side computes a linear combination of the basis functions (one per constraint) evaluated at constraint location j. That is, it evaluates at c_j the RBF interpolant determined by coefficients w_i. Then the equation asks this interpolant to assume the constraint value (epsilon, 0, or -epsilon).

Notice, since the are as many coefficients (basis functions) as constraints, the system is square and can be solved directly *without weighted least squares*. Thus there is no approximation: the final interpolant will satisfy the constraints exactly.

For consistency with the MLS equations later on in the slides and in the assignment, these weights w_i should actually be called "a_j", and the basis functions should be called "b_j = phi(||x - c_j||)." Note, phi is a function of distance, not squared distance.

**Comment by oveddan** [comment]
thank you for clarifying!
