### ISSUE TITLE
[Assignment 2]questions about MLS

### ISSUE THREAD

**Issue by peiyueY** [danielepanozzo/gp-old#50]
Hi, I have two questions about MLS:

1. In Wendland Weights, how do we choose the value of "h"?

2. How to use spatial index in 2.2?

Thanks!

**Comment by danielepanozzo** [comment]
1. The Wendland function is defined only in the interval [0,h]. You should pick an h that is sufficient to capture enough points so that the MLS fit will have enough points to compute the local fit. It is a parameter that you will have to tweak on the different models, and depends on the density of the point cloud.

2. You need to use the spatial index to find the points for which the Wendland function is not 0, i.e. find all the points which are closer than h to the evaluation point.
