### ISSUE TITLE
[Assignment 4] Key 'E' assertion failed

### ISSUE THREAD

**Issue by potato1996** [danielepanozzo/gp-old#56]
Hi Professor,

I'm playing around with the given assignment 4 code. It seems that key '[' and ']' are used to rotate the constrain, and 'Q' and 'W' are used to scale it. However when I press key 'E' it will trigger an assertion failure (pasted below). Is it an expected behavior? If so what should 'E' expected to do? Thanks!  

nrosy_field_bin: /home/potato/workspace/gp/gm-assignment-4-potato1996/external/libigl/external/eigen/Eigen/src/Core/Block.h:118: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1; int BlockCols = -1; bool InnerPanel = false; Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.

**Comment by jiangzhongshi** [comment]
Hi,

Thanks for the report!
I can reproduce this problem, it comes from https://github.com/NYUGraphics/GM_Assignment_4/blob/master/src/main.cpp#L176-L179

where `bc` is set to the wrong row number, and it can be fixed with https://github.com/NYUGraphics/GM_Assignment_4/commit/5f93c42ced45bf562aa44fea21b20800236aabb8
@danielepanozzo  Can you confirm this?

**Comment by potato1996** [comment]
Thank you! If I understand correctly 'E' should be able to remove the selected constrain?

**Comment by jiangzhongshi** [comment]
Yes that’s correct

**Comment by danielepanozzo** [comment]
👍
