### ISSUE TITLE
[Slides 08] Why the u, v function from the "spring" method is harmonic?

### ISSUE THREAD

**Issue by potato1996** [danielepanozzo/gp-old#64]
I think I must missed something between Slides 08, page 48-62...correct me if I made anything wrong..

In my understanding we need to solve the Laplacian equation to "flatten" the surface. So we need to find out the weights in L. And also I understand the deduction of minimizing the "spring energy" from page 50-62. But I don't understand what is the relationship between the Laplacian equation and the spring energy. Specifically:

1. What's the relationship between minimizing the spring energy and constructing the Laplacian L matrix? In the spring method we solve the boundary condition by separating "boundary-boundary", "boundary-inner" and "inner-inner" edges. But why this corresponds to the boundary condition in the Laplacian equation?
3. Why the u, v functions are harmonic (are they piece wise linear?)
3. Why both k = 1 or cotan both satisfied the harmonic condition? Will arbitrary k satisfy that or there's only some of them?

Thank you!

**Comment by jiangzhongshi** [comment]
Hi,

1. The spring method, in the matrix form, becomes
```
min u' L u
s.t. u_b = c
```
Different choices of L (uniform/cotan) correspond to different constants for spring.
2. 
Harmonic function https://en.wikipedia.org/wiki/Harmonic_function is defined as the function that satisfies Laplacian function (and it will be in general twice differentiable). In our context, with everything discrete, we extend it to "discrete" harmonic function, since it solves the "discrete" Laplacian equation.
3. Since we have a relaxed definition of discrete harmonic (solution of some laplacian equation), you are allowed to call them harmonic with respect to different discretization. But we normally call the k_ij=1 as Tutte and cotan as harmonic, when there's a need to distinguish.

**Comment by potato1996** [comment]
Hi Zhongshi,

I just came up a following question on that: here it seems like we construct the Matrix L just using the uniform/cotangent "Stiffness Matrix" rather than using the real "Laplacian Matrix". The reason is the "Mass Matrix" is diagonal thus it will not affect the result of solving Lu = 0, so we simply ignore it here. Is that correct?

Thanks again!
